# Generated by Django 4.2.1 on 2023-05-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicGymnasium',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default='yNf8U6Pp5ObS', max_length=12, primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=100, unique=True)),
                ('prefecture', models.CharField(max_length=20)),
                ('municipality', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=255)),
                ('training_room_flag', models.BooleanField()),
            ],
            options={
                'db_table': 'public_gymnasium',
                'ordering': ['prefecture'],
            },
        ),
    ]
