# Generated by Django 4.2.1 on 2023-05-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicGymnasium',
            fields=[
                ('id', models.CharField(default='KgnBwCql6hPKkAU9M7tjxS', max_length=22, primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=100)),
                ('prefecture', models.CharField(max_length=20)),
                ('municipality', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('training_room_flag', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'public_gymnasium',
                'ordering': ['prefecture'],
            },
        ),
    ]
