# Generated by Django 4.1.10 on 2023-08-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublicGymnasium",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default="DOHP7hLWhCqFW61FrFgxY8",
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("facility_name", models.CharField(max_length=100)),
                ("prefecture", models.CharField(max_length=20)),
                ("municipality", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("telephone", models.CharField(blank=True, max_length=30, null=True)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("training_room_flag", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "public_gymnasium",
                "ordering": ["prefecture"],
            },
        ),
    ]
